#include<iostram.h>
void main(){
 int a[100],search,n,f=0;
 clock_t start,end;
 start=clock();
 cout<<"enter n";
 cin>>n
     for(int i=0; i<n; i++)
     cin>>a[i];
     cout<<a[i];
     cout<<a[1];
     cout<<"enter search "<<search<<endl;
 for(i=0; i<n; i++)
 {
 if(a[i]==search)
 cout<<"present at index "<<i<<endl;
 f=1;
 if(f==0)
 cout<<"element not found"<<endl;

 }






 end=clock();
}